"""
Slack integration for posting incident summaries.
"""

from __future__ import annotations

import json
from typing import Any

import requests

from denoiser.logging import get_logger

logger = get_logger(__name__)


class SlackNotifier:
    """Sends incident reports to a Slack channel via Webhook."""

    def __init__(self, webhook_url: str | None = None) -> None:
        self.webhook_url = webhook_url

    def notify(self, payload: dict[str, Any] | str) -> bool:
        """Send a notification to Slack.

        Parameters
        ----------
        payload : dict[str, Any] | str
            The message to send. If a string, it will be wrapped in a basic Slack block.
            If a dict, it is sent as-is (standard Slack Block Kit).

        Returns
        -------
        bool
            True if successful, False otherwise.
        """
        if not self.webhook_url:
            logger.warning("Slack notification attempted but no Webhook URL provided.")
            return False

        if isinstance(payload, str):
            # Basic fallback for raw text
            slack_data = {
                "text": "Semantic Log De-Noiser Report",
                "blocks": [
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": payload
                        }
                    }
                ]
            }
        else:
            slack_data = payload

        try:
            logger.info("Sending report to Slack...")
            response = requests.post(
                self.webhook_url,
                data=json.dumps(slack_data),
                headers={'Content-Type': 'application/json'},
                # `requests` has no default timeout, so without this the call
                # blocks forever against a host that accepts the connection and
                # never answers — which is what a partial Slack outage looks
                # like. Every worker thread that posted a report would be held,
                # one per run, until analysis stopped entirely, with nothing
                # timing out and nothing to alert on.
                timeout=10,
            )
            response.raise_for_status()
            logger.info("Successfully posted to Slack.")
            return True
        except Exception as e:
            logger.error(f"Failed to post to Slack: {e}")
            return False

    def format_report_for_slack(
        self,
        total_logs: int,
        intelligence: dict[str, Any] | None = None,
        anomalies_found: bool = False
    ) -> dict[str, Any]:
        """Convert analysis results into Slack Block Kit format."""

        blocks = [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": "🚀 Semantic Log Analysis Complete",
                    "emoji": True
                }
            },
            {
                "type": "section",
                "fields": [
                    {"type": "mrkdwn", "text": f"*Total Logs:* {total_logs}"},
                    {"type": "mrkdwn", "text": f"*Anomalies:* {'🔴 Found' if anomalies_found else '🟢 None'}"}
                ]
            }
        ]

        if intelligence:
            summary = intelligence.get("incident_summary", "N/A")
            domain = intelligence.get("failure_domain", "N/A")

            blocks.append({"type": "divider"})
            blocks.append({
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*AI Intelligence Summary*\n*Failure Domain:* `{domain}`\n\n{summary}"
                }
            })

            hints = intelligence.get("root_cause_hints")
            if hints:
                hints_str = "\n".join([f"• {h}" for h in hints]) if isinstance(hints, list) else str(hints)

                blocks.append({
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": f"*Next Steps:*\n{hints_str}"
                    }
                })

        blocks.append({"type": "divider"})
        blocks.append({
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": "Generated by *Semantic Log De-Noiser CLI*"
                }
            ]
        })

        return {"blocks": blocks}
