"""baseline schema from models

Revision ID: 773789731d39
Revises: 
Create Date: 2026-07-23 01:15:14.394905
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '773789731d39'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webhook_id', sa.String(), nullable=True),
    sa.Column('alert_fingerprint', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_logs_alert_fingerprint'), 'alert_logs', ['alert_fingerprint'], unique=False)
    op.create_index(op.f('ix_alert_logs_id'), 'alert_logs', ['id'], unique=False)
    op.create_index(op.f('ix_alert_logs_timestamp'), 'alert_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_alert_logs_webhook_id'), 'alert_logs', ['webhook_id'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('raw_lines', sa.Integer(), nullable=True),
    sa.Column('cluster_count', sa.Integer(), nullable=True),
    sa.Column('reduction_ratio', sa.Float(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('clusters_snapshot', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_runs_id'), 'analysis_runs', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_tenant_id'), 'analysis_runs', ['tenant_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('billing_meters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('total_logs_ingested', sa.Integer(), nullable=True),
    sa.Column('total_bytes_ingested', sa.Integer(), nullable=True),
    sa.Column('total_traces_ingested', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_meters_id'), 'billing_meters', ['id'], unique=False)
    op.create_index(op.f('ix_billing_meters_tenant_id'), 'billing_meters', ['tenant_id'], unique=False)
    op.create_table('dashboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('layout', sa.JSON(), nullable=True),
    sa.Column('widgets', sa.JSON(), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=True),
    sa.Column('default_time_range', sa.String(), nullable=True),
    sa.Column('template_variables', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboards_id'), 'dashboards', ['id'], unique=False)
    op.create_index(op.f('ix_dashboards_tenant_id'), 'dashboards', ['tenant_id'], unique=False)
    op.create_table('deployment_markers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_markers_id'), 'deployment_markers', ['id'], unique=False)
    op.create_index(op.f('ix_deployment_markers_service'), 'deployment_markers', ['service'], unique=False)
    op.create_index(op.f('ix_deployment_markers_tenant_id'), 'deployment_markers', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_deployment_markers_timestamp'), 'deployment_markers', ['timestamp'], unique=False)
    op.create_table('extracted_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_metrics_id'), 'extracted_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_extracted_metrics_rule_id'), 'extracted_metrics', ['rule_id'], unique=False)
    op.create_index(op.f('ix_extracted_metrics_tenant_id'), 'extracted_metrics', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_extracted_metrics_timestamp'), 'extracted_metrics', ['timestamp'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('remediation_hints', sa.JSON(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('total_logs', sa.Integer(), nullable=True),
    sa.Column('cluster_count', sa.Integer(), nullable=True),
    sa.Column('is_predictive', sa.Boolean(), nullable=True),
    sa.Column('forecasted_depletion_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_index(op.f('ix_incidents_tenant_id'), 'incidents', ['tenant_id'], unique=False)
    op.create_table('integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrations_id'), 'integrations', ['id'], unique=False)
    op.create_index(op.f('ix_integrations_tenant_id'), 'integrations', ['tenant_id'], unique=False)
    op.create_table('metric_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('aggregation', sa.String(), nullable=True),
    sa.Column('window_seconds', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_rules_id'), 'metric_rules', ['id'], unique=False)
    op.create_index(op.f('ix_metric_rules_tenant_id'), 'metric_rules', ['tenant_id'], unique=False)
    op.create_table('monitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('threshold_critical', sa.Float(), nullable=True),
    sa.Column('threshold_warning', sa.Float(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('muted_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitors_id'), 'monitors', ['id'], unique=False)
    op.create_index(op.f('ix_monitors_tenant_id'), 'monitors', ['tenant_id'], unique=False)
    op.create_table('notebooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('cells', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notebooks_id'), 'notebooks', ['id'], unique=False)
    op.create_index(op.f('ix_notebooks_tenant_id'), 'notebooks', ['tenant_id'], unique=False)
    op.create_table('runbook_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('runbook_id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('logs', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runbook_executions_id'), 'runbook_executions', ['id'], unique=False)
    op.create_index(op.f('ix_runbook_executions_incident_id'), 'runbook_executions', ['incident_id'], unique=False)
    op.create_index(op.f('ix_runbook_executions_runbook_id'), 'runbook_executions', ['runbook_id'], unique=False)
    op.create_table('runbooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('trigger_condition', sa.JSON(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runbooks_id'), 'runbooks', ['id'], unique=False)
    op.create_index(op.f('ix_runbooks_tenant_id'), 'runbooks', ['tenant_id'], unique=False)
    op.create_table('saved_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('query_text', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_queries_id'), 'saved_queries', ['id'], unique=False)
    op.create_table('slo_data_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slo_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('good_events', sa.Integer(), nullable=True),
    sa.Column('total_events', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slo_data_points_id'), 'slo_data_points', ['id'], unique=False)
    op.create_index(op.f('ix_slo_data_points_slo_id'), 'slo_data_points', ['slo_id'], unique=False)
    op.create_index(op.f('ix_slo_data_points_timestamp'), 'slo_data_points', ['timestamp'], unique=False)
    op.create_table('slos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('sli_type', sa.String(), nullable=False),
    sa.Column('target_percentage', sa.Float(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slos_id'), 'slos', ['id'], unique=False)
    op.create_index(op.f('ix_slos_service'), 'slos', ['service'], unique=False)
    op.create_index(op.f('ix_slos_tenant_id'), 'slos', ['tenant_id'], unique=False)
    op.create_table('spans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('span_id', sa.String(), nullable=False),
    sa.Column('parent_span_id', sa.String(), nullable=True),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('operation_name', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('status_code', sa.String(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spans_id'), 'spans', ['id'], unique=False)
    op.create_index(op.f('ix_spans_parent_span_id'), 'spans', ['parent_span_id'], unique=False)
    op.create_index(op.f('ix_spans_service_name'), 'spans', ['service_name'], unique=False)
    op.create_index(op.f('ix_spans_span_id'), 'spans', ['span_id'], unique=False)
    op.create_index(op.f('ix_spans_tenant_id'), 'spans', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_spans_trace_id'), 'spans', ['trace_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('environment_access', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_spans_trace_id'), table_name='spans')
    op.drop_index(op.f('ix_spans_tenant_id'), table_name='spans')
    op.drop_index(op.f('ix_spans_span_id'), table_name='spans')
    op.drop_index(op.f('ix_spans_service_name'), table_name='spans')
    op.drop_index(op.f('ix_spans_parent_span_id'), table_name='spans')
    op.drop_index(op.f('ix_spans_id'), table_name='spans')
    op.drop_table('spans')
    op.drop_index(op.f('ix_slos_tenant_id'), table_name='slos')
    op.drop_index(op.f('ix_slos_service'), table_name='slos')
    op.drop_index(op.f('ix_slos_id'), table_name='slos')
    op.drop_table('slos')
    op.drop_index(op.f('ix_slo_data_points_timestamp'), table_name='slo_data_points')
    op.drop_index(op.f('ix_slo_data_points_slo_id'), table_name='slo_data_points')
    op.drop_index(op.f('ix_slo_data_points_id'), table_name='slo_data_points')
    op.drop_table('slo_data_points')
    op.drop_index(op.f('ix_saved_queries_id'), table_name='saved_queries')
    op.drop_table('saved_queries')
    op.drop_index(op.f('ix_runbooks_tenant_id'), table_name='runbooks')
    op.drop_index(op.f('ix_runbooks_id'), table_name='runbooks')
    op.drop_table('runbooks')
    op.drop_index(op.f('ix_runbook_executions_runbook_id'), table_name='runbook_executions')
    op.drop_index(op.f('ix_runbook_executions_incident_id'), table_name='runbook_executions')
    op.drop_index(op.f('ix_runbook_executions_id'), table_name='runbook_executions')
    op.drop_table('runbook_executions')
    op.drop_index(op.f('ix_notebooks_tenant_id'), table_name='notebooks')
    op.drop_index(op.f('ix_notebooks_id'), table_name='notebooks')
    op.drop_table('notebooks')
    op.drop_index(op.f('ix_monitors_tenant_id'), table_name='monitors')
    op.drop_index(op.f('ix_monitors_id'), table_name='monitors')
    op.drop_table('monitors')
    op.drop_index(op.f('ix_metric_rules_tenant_id'), table_name='metric_rules')
    op.drop_index(op.f('ix_metric_rules_id'), table_name='metric_rules')
    op.drop_table('metric_rules')
    op.drop_index(op.f('ix_integrations_tenant_id'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_id'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_incidents_tenant_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_extracted_metrics_timestamp'), table_name='extracted_metrics')
    op.drop_index(op.f('ix_extracted_metrics_tenant_id'), table_name='extracted_metrics')
    op.drop_index(op.f('ix_extracted_metrics_rule_id'), table_name='extracted_metrics')
    op.drop_index(op.f('ix_extracted_metrics_id'), table_name='extracted_metrics')
    op.drop_table('extracted_metrics')
    op.drop_index(op.f('ix_deployment_markers_timestamp'), table_name='deployment_markers')
    op.drop_index(op.f('ix_deployment_markers_tenant_id'), table_name='deployment_markers')
    op.drop_index(op.f('ix_deployment_markers_service'), table_name='deployment_markers')
    op.drop_index(op.f('ix_deployment_markers_id'), table_name='deployment_markers')
    op.drop_table('deployment_markers')
    op.drop_index(op.f('ix_dashboards_tenant_id'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_id'), table_name='dashboards')
    op.drop_table('dashboards')
    op.drop_index(op.f('ix_billing_meters_tenant_id'), table_name='billing_meters')
    op.drop_index(op.f('ix_billing_meters_id'), table_name='billing_meters')
    op.drop_table('billing_meters')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_analysis_runs_tenant_id'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_alert_logs_webhook_id'), table_name='alert_logs')
    op.drop_index(op.f('ix_alert_logs_timestamp'), table_name='alert_logs')
    op.drop_index(op.f('ix_alert_logs_id'), table_name='alert_logs')
    op.drop_index(op.f('ix_alert_logs_alert_fingerprint'), table_name='alert_logs')
    op.drop_table('alert_logs')
    # ### end Alembic commands ###
