#!/usr/bin/env bash
#
# One-command bring-up for the SemanticOS docker-compose stack.
#
#   ./deploy/bootstrap.sh
#
# Generates a .env with strong random secrets on first run (idempotent — it never
# overwrites an existing .env), then builds and starts the full stack.
#
set -euo pipefail
cd "$(dirname "$0")/.."

ENV_FILE=".env"

rand() { openssl rand -hex "${1:-24}"; }

if [[ ! -f "$ENV_FILE" ]]; then
  echo "→ No .env found. Generating one with random secrets..."
  ADMIN_PASSWORD="$(rand 9)"            # the admin login password (printed below)
  cat > "$ENV_FILE" <<EOF
# Generated by deploy/bootstrap.sh — keep this file secret, do NOT commit it.

# --- Infrastructure credentials ---
POSTGRES_USER=postgres
POSTGRES_PASSWORD=$(rand 24)
POSTGRES_DB=semanticos
CLICKHOUSE_USER=default
CLICKHOUSE_PASSWORD=$(rand 24)
CLICKHOUSE_DB=default
MINIO_ROOT_USER=admin
MINIO_ROOT_PASSWORD=$(rand 24)

# --- Application auth ---
JWT_SECRET_KEY=$(rand 48)
SEMANTICOS_ADMIN_PASSWORD=${ADMIN_PASSWORD}
INGEST_API_KEY=$(rand 24)

# --- Browser origins allowed to call the API (CORS) ---
# Same-origin (UI behind the bundled nginx). Add your public URL(s) here, and add
# your Vercel URL if you host the frontend there, e.g.:
#   CORS_ALLOWED_ORIGINS=http://localhost,https://localhost,https://your-app.vercel.app
CORS_ALLOWED_ORIGINS=http://localhost,https://localhost
EOF
  chmod 600 "$ENV_FILE"
  echo "→ Wrote $ENV_FILE"
  echo ""
  echo "  ┌────────────────────────────────────────────────────────────┐"
  echo "  │  ADMIN LOGIN                                                │"
  echo "  │  email:    admin@semanticos.io                             │"
  printf "  │  password: %-48s│\n" "${ADMIN_PASSWORD}"
  echo "  │  (also saved as SEMANTICOS_ADMIN_PASSWORD in .env)         │"
  echo "  └────────────────────────────────────────────────────────────┘"
  echo ""
else
  echo "→ Using existing .env"
fi

# Generate a self-signed TLS cert for nginx if one isn't present. The certs are
# not committed (a private key must never be in git), so a fresh clone needs this
# or nginx fails to start.
CERT_DIR="nginx/certs"
if [[ ! -f "$CERT_DIR/localhost.crt" || ! -f "$CERT_DIR/localhost.key" ]]; then
  echo "→ Generating self-signed TLS certificate for nginx..."
  mkdir -p "$CERT_DIR"
  openssl req -x509 -newkey rsa:2048 -nodes -days 825 \
    -keyout "$CERT_DIR/localhost.key" -out "$CERT_DIR/localhost.crt" \
    -subj "/CN=semanticos" \
    -addext "subjectAltName=DNS:localhost,IP:127.0.0.1" >/dev/null 2>&1
  echo "→ Wrote $CERT_DIR/localhost.{crt,key} (self-signed — browsers warn; accept to proceed)"
fi

echo "→ Building and starting the stack (this is slow on first run — ML deps)..."
docker compose up -d --build

echo ""
echo "→ Stack starting. Watch health with:  docker compose ps"
echo "→ Once healthy, open:  https://localhost  (self-signed cert — accept the warning)"
echo "→ API health:          https://localhost/api/health"
