apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "semanticos.fullname" . }}-worker
  labels:
    {{- include "semanticos.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "semanticos.name" . }}-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "semanticos.name" . }}-worker
        app.kubernetes.io/component: worker
    spec:
      serviceAccountName: {{ include "semanticos.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: worker
          image: "{{ .Values.image.apiRepository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          command: ["celery", "-A", "denoiser.workers.analysis_worker:celery_app", "worker", "-B", "--pool=solo", "--loglevel=info"]
          env:
            {{- include "semanticos.env" . | nindent 12 }}
          resources:
            {{- toYaml .Values.resources.worker | nindent 12 }}
